name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: dpkg / rpm prep (debug)
      run: echo "sudo -E apt-get install -y uuid-dev uuid libuuid1 libaio-dev libaio1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0"
    - name: dpkg / rpm prep
      run: sudo -E apt-get install -y uuid-dev uuid libuuid1 libaio-dev libaio1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0
# default build
    - make: prepare.sh
      run: ./prepare.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j 4
    - name: make check
      run: make check
# asan build
    - name: distclean
      run: make distclean
    - make: prepare.sh
      run: ./prepare.sh
    - name: configure with address-sanitizer
      run: ./configure --enable-asan --enable-devel
    - name: make
      run: make -j 4
    - name: make check
      run: make check
# clang build
    - name: distclean
      run: make distclean
    - make: prepare.sh
      run: ./prepare.sh
    - name: configure CC=clang
      run: ./configure CC=clang
    - name: make
      run: make -j 4
    - name: make check
      run: make check
# other targets
    - name: uncrustify version (debug)
      run: uncrustify -v
    - name: make autofmt-check
      run: make autofmt-check
# gather some system stats
    - name: memory
      run: free
    - name: net
      run: ip a
    - name: disk
      run: df -h
    - name: process
      run: ps auxfw
    - name: cpu
      run: cat /proc/cpuinfo
