name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
    - name: dpkg / rpm prep (debug)
      run: echo "sudo -E apt-get install -y uuid-dev uuid libuuid1 libaio-dev libaio1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0"
    - name: dpkg / rpm prep
      run: sudo -E apt-get install -y uuid-dev uuid libuuid1 libaio-dev libaio1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0
    - name: make
      run: make -j 4
    - name: make check
      run: make check
    - name: clean
      run: make clean
    - name: make asan-check
      run: make asan-check
    - name: uncrustify version (debug)
      run: uncrustify -v
    - name: make autofmt-check
      run: make autofmt-check
    - name: net
      run: ip a
    - name: disk
      run: df -h
    - name: process
      run: ps auxfw
    - name: cpu
      run: cat /proc/cpuinfo
