name: holon_niova_workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./code

    - name: apt update
      run: sudo apt update
    - name: dpkg / rpm prep (debug)
      run: echo "sudo -E apt-get install -y uuid-dev uuid libuuid1 libaio-dev libaio1 libgcrypt20 openssl libssl-dev `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0"
    - name: dpkg / rpm prep
      run: sudo -E apt-get install -y uuid-dev uuid libuuid1 libaio-dev libaio1 libgcrypt20 openssl libssl-dev python3-pip python3-setuptools `apt-cache search librocksdb | awk '{print $1}'` uncrustify libasan5 libtsan0
    - name: make
      run: cd ./code && ./prepare.sh && ./configure && make

    - name: Create build dir
      run: mkdir ./build_dir

    - name: Copy niova files
      run: cp ./code/Dockerfile ./build_dir

    - name: Copy niova binaries
      run: cp ./code/test/*-reference-server ./build_dir && cp ./code/test/*-reference-client ./build_dir && cp ./code/scripts/run-recipes.sh ./build_dir

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
       repository: 00pauln00/holon
       #ref: testing_with_niova_repo
       token: ${{ secrets.HOLON_NIOVA_CI_21_12_2020 }} # 'GitHub_PAT' is a secret that contains your PAT
       path: ./holon

    - name: Install python libraries
      run: sudo -E -H pip3 install setuptools func_timeout sockets psutil dpath ansible jmespath

    - name: Copy holon repo
      run: cp -r ./holon ./build_dir

    - name: Create log directory for storing holon logs
      run: mkdir  /home/runner/work/niovad/niovad/holon_log

    - name: List build directory
      run: ls -l /home/runner/work/niovad/niovad/build_dir

    - name:  run leader_overthrow
      run: cd ./build_dir/holon/ && sh ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon' '/home/runner/work/niovad/niovad/build_dir/' '/home/runner/work/niovad/niovad/holon_log' 5
      env:
        ANSIBLE_LOOKUP_PLUGINS: /home/runner/work/niovad/niovad/build_dir/holon
        PYTHONPATH: /home/runner/work/niovad/niovad/build_dir/holon
        NIOVA_BIN_PATH: /home/runner/work/niovad/niovad/build_dir/

    - name: Archive the recipe results
      uses: actions/upload-artifact@v2
      with:
         name: test-recipe-report
         path: /home/runner/work/niovad/niovad/holon_log
      if: failure()
